apiVersion: v1
kind: Namespace
metadata:
  name: op-host-manager
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: op-host-manager
  namespace: op-host-manager
spec:
  selector:
    matchLabels:
      name: op-host-manager
  template:
    metadata:
      labels:
        name: op-host-manager
    spec:
      serviceAccountName: op-host-manager-sa
      containers:
      - name: op-host-manager
        image: your-registry/node-labeler:v1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: op-host-manager-sa
  namespace: op-host-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: op-host-manager-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: op-host-manager-role-binding
subjects:
- kind: ServiceAccount
  name: op-host-manager-sa
  namespace: op-host-manager
roleRef:
  kind: ClusterRole
  name: op-host-manager-role
  apiGroup: rbac.authorization.k8s.io
